### ISSUE TITLE
Unable to send transactions on bbn-test-4

### ISSUE THREAD

**Issue by ljunb** [babylonchain/networks#247]
Hello, our wallet has integrated Testnet 3 before. After testing, address derivation, private key generation, gas estimation and sending transactions can all work properly. Recently, we migrated from Testnet 3 to Testnet 4, but we have not found the corresponding RPC node. After changing the chain id to `bbn-test-4` and using `https://babylon-testnet-rpc.polkachu.com:443` as the RPC node, the following error is prompted when sending transactions:
```typescript
[Error: Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; 
please verify account number (0) and chain-id (bbn-test-3): (unable to verify single signer signature): unauthorized]
```
Besides, we're using cosmjs to implement this. Currently, we can get account information, balance, and gas estimation normally, but we cannot send transactions. The address for testing is `bbn199xewvwqmfue5r63prac0sy8apejjtux4qz434`, and it's a bit strange that I can't see the account related records in the [explorer](https://testnet.babylon.explorers.guru/account/bbn199xewvwqmfue5r63prac0sy8apejjtux4qz434) now. 

I hope the team can provide some guiding opinions, thank you!

**Comment by RafilxTenfen** [comment]
There is no Babylon chain on this testnet, it is focused on Bitcoin only
