### ISSUE TITLE
have no permission to push the json and sig configure file to bbn-test-4

### ISSUE THREAD

**Issue by riverchen1982** [babylonchain/networks#283]
Hi， According to the documentation you provided, I have deployed bbn-test-4 finality-provider locally。but when i  push the json and sig configure file to bbn-test-4, the git tell me no permission, I switched to my colleague's account and encountered the same problem.Can you tell me how to apply for this permission? Or give me an invitation, thanks!

**Comment by imamkholid99** [comment]
Nyimak

**Comment by RafilxTenfen** [comment]
closing it for now as it did not had response
